#!/bin/bash
#

declare -r WA2WT="$( readlink -f $0 )"
declare -r PYTHON="$( which python 2>/dev/null )"

if [ -z "${PYTHON}" ]; then
  echo "[error] No program point to command 'python'!"
  echo "[tips] Please add python3 to the 'PATH' ..."
  exit 1
fi

python_version=$(python --version | grep 'Python 3')
if [ -z "${python_version}" ]; then
  echo "[error] Please make sure the command 'python' point to python3."
  exit 1
fi

${PYTHON} ${WA2WT%/*}/wa2wt.py
